# Site
name: 'Bloggingwithravi'
description: 'I will take you on the fabulous world of exploration. Travel, culture, lifestyle. Eat, Pray, Love!'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: '/Ravijoshiji.github.io/Ravijoshi.github.io/'
disqus: 'bloggingwithravi-1'
email: 'bloggingwithraviOO7@gmail.com'
mailchimp-list: 'https://bloggingwithravi.us4.list-manage.com/subscribe/post?u=6624b5372168533b3b46d0d01&amp;id=10671579f2'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-archives
  
 # Google Analytics
google_analytics: 'UA-143528900-5'
  
  
authors:
    sal:
      name:           Ravi Joshi
      site:           https://bloggingwithravi.com
      avatar:         /assets/images/20201127_115441.ico
      bio:            "i've always been fiddling with tech for as long as i remember. This naturally transitioned into helping friends with their tech problems and then into tech blogging"
      email:          bloggingwithraviOO7@gmail.com
      twitter:        https://mobile.twitter.com/bloggingwthravi

#     jane:
      name:           Ravi Joshi
      site:           https://bloggingwithravi.com
      avatar:         /assets/images/20201127_115441.ico
      bio:           "I've always been fiddling with tech for as long as i remember. This naturally transitioned into helping friends with their tech problems and then into tech blogging"
      email:          bloggingwithraviOO7@gmail.com
      twitter:        https://mobile.twitter.com/bloggingwthravi 
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sal
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:title/'



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
